---
title: "Pseudobulk"
output: html_document
---

#Load R Packages
```{r}
library(reticulate)
library(DESeq2)
library(scater)
library(SingleCellExperiment)
library(zellkonverter)
library(data.table)
library(tibble)
library(dplyr)

```


#Load Python Directory
```{r}
use_python("/mnt/ufs18/home-183/cholicog/miniconda3/envs/scvi-env/bin/python")
```

#Load Python Packages
```{r}
ad <- import("anndata")
```

#Import Data
```{r}
adata <- ad$read_h5ad("/mnt/ufs18/home-183/cholicog/snRNAseq_Analysis/01_Libraries_Integration_and_Analysis---scVI/Adata_Objects/01d_AllGenes_Clustered_And_Annotated_Cells.h5ad")
```



# Convert Anndata to SingleCell Experiment Format and Create Pseudobulk Data
```{r}
sce <- zellkonverter::AnnData2SCE(
                            adata,
                            X_name = NULL,
                            layers = TRUE,
                            uns = FALSE,
                            var = TRUE,
                            obs = TRUE,
                            varm = FALSE,
                            obsm = FALSE,
                            varp = FALSE,
                            obsp = FALSE,
                            raw = FALSE,
                            skip_assays = FALSE,
                            hdf5_backed = FALSE,
                            verbose = TRUE
                            )

#Export sample names
ids <- sce$OrigIdent_Celltype

# Aggregate expression values by sample ID
pseudobulk <- aggregateAcrossCells(sce, ids, statistics="sum")

# Print the pseudobulk data
print(pseudobulk)
```


```{r}
#Make copy of pseudobulk data
pseudobulk2 <- pseudobulk
pseudobulk2$Dose_Time <- as.factor(pseudobulk2$Dose_Time)

#Export pseudobulk data as Dataframe
pb_export <- as.data.frame(pseudobulk2@assays@data@listData$counts)


#Reindex rows (Library_Celltype) and reorder columns alphabetically (Genes)
pb_export <- tibble::rownames_to_column(pb_export, var = "Index")
pb_export <- pb_export[ ,order(colnames(pb_export))]

#Create metadata Dataframe and Trim Down
metadata <- colData(pseudobulk2)
metadata2 <- metadata[c('OrigIdent_Celltype', 'Dose', 'Time', 'Dose_Time','OrigIdent', 'Celltype')]


metadata5 <- metadata2

#Reindex Metadata adn reorder columns
row.names(metadata5) <- metadata5$OrigIdent_Celltype
metadata5 <- metadata5[order(metadata5$OrigIdent_Celltype),]
```


####################
### Deseq2 for loop for each cell type. 
####################
```{r}
cell_types <- c('Hepatocytes', 'ECs', 'HSCs', 'Macrophages', 'B Cells', 'T Cells', 'PFs', 'Cholangiocytes', 'Neutrophils', 'pDCs')

# Loop over each cell type
for (cell_type in cell_types) {
  # Modify the cell type name
  cell_type_no_space <- gsub(" ", "_", cell_type)
  
  # Print the "starting" message
  cat("Starting analysis for", cell_type, "\n")
  
  # Subset the data based on the cell type
  pb_export_subset <- pb_export[, grepl(cell_type, colnames(pb_export))]
  
  # Add index column
  pb_export_subset <- cbind(Index = index_col, pb_export_subset)
  
  # Set row names
  row.names(pb_export_subset) <- pb_export_subset$Index
  pb_export_subset <- pb_export_subset[, -1]
  
  # Calculate the row sums
  row_sums <- rowSums(pb_export_subset)
  
  # Add row sums as a new column to pb_export_subset
  pb_export_subset$RowSums <- row_sums
  
  # Filter rows with values >= 50 in the "RowSums" column
  pb_export_subset_50count <- subset(pb_export_subset, RowSums >= 50)
  
  # Reorder rows based on values in the "RowSums" column
  pb_export_subset_50count <- pb_export_subset_50count %>% arrange(desc(RowSums))
  
  # Calculate the threshold for removing the bottom 10% of rows
  threshold <- quantile(pb_export_subset_50count$RowSums, 0.1)
  
  # Remove the bottom 10% of rows based on the threshold
  pb_export_subset_50count_trimmed <- pb_export_subset_50count[pb_export_subset_50count$RowSums >= threshold, ]
  
  #Drop the "RowSums" column from pb_export_subset_50count_trimmed
  pb_export_subset_50count_trimmed <- subset(pb_export_subset_50count_trimmed, select = -c(RowSums))  
  
  # Subset metadata based on cell type
  metadata_subset <- metadata5[grepl(cell_type, metadata5$OrigIdent_Celltype), ]
  
  # Create DESeqDataSet
  dds <- DESeqDataSetFromMatrix(countData = pb_export_subset_50count_trimmed, colData = metadata_subset, design = ~ Dose + Time + Dose:Time)
  
  # Run DESeq2 analysis
  dds <- DESeq(dds, test = "LRT", reduced = ~ Dose + Time)
  
  # Extract results
  res <- results(dds)
  
  # Print the "Exporting" message
  cat("Exporting analysis for", cell_type, "\n")
  
  # Write results to file
  write.table(res, file = paste0(cell_type_no_space, "_LRT.txt"), sep = '\t', quote = FALSE)
}
```







####################
### Explore X Celltype
####################
```{r}
cell_type = "Macrophage"

# Modify the cell type name
cell_type_no_space <- gsub(" ", "_", cell_type)

# Subset the data based on the cell type
pb_export_subset <- pb_export[, grepl(cell_type, colnames(pb_export))]

# Add index column
pb_export_subset <- cbind(Index = index_col, pb_export_subset)

# Set row names
row.names(pb_export_subset) <- pb_export_subset$Index
pb_export_subset <- pb_export_subset[, -1]

# Calculate the row sums
row_sums <- rowSums(pb_export_subset)

# Add row sums as a new column to pb_export_subset
pb_export_subset$RowSums <- row_sums

# Filter rows with values >= 50 in the "RowSums" column
pb_export_subset_50count <- subset(pb_export_subset, RowSums >= 50)

# Reorder rows based on values in the "RowSums" column
pb_export_subset_50count <- pb_export_subset_50count %>% arrange(desc(RowSums))

# Calculate the threshold for removing the bottom 10% of rows
threshold <- quantile(pb_export_subset_50count$RowSums, 0.1)

# Remove the bottom 10% of rows based on the threshold
pb_export_subset_50count_trimmed <- pb_export_subset_50count[pb_export_subset_50count$RowSums >= threshold, ]

#Drop the "RowSums" column from pb_export_subset_50count_trimmed
pb_export_subset_50count_trimmed <- subset(pb_export_subset_50count_trimmed, select = -c(RowSums))  

# Subset metadata based on cell type
metadata_subset <- metadata5[grepl(cell_type, metadata5$OrigIdent_Celltype), ]






# Deseq2 Analysis
ddsTC  <- DESeqDataSetFromMatrix(countData=pb_export_subset_50count_trimmed, 
                               colData=metadata_subset, 
                               design= ~  Dose + Time + Dose:Time)


ddsTC <- DESeq(ddsTC, test="LRT", reduced = ~ Dose + Time)


# Extract results
resTC <- results(ddsTC)


resTC$symbol <- row.names(ddsTC)
head(resTC[order(resTC$padj),], 4)

fiss <- plotCounts(ddsTC, which.min(resTC$padj),  #can replace which.min(resTC$padj) with "GeneSymbol"
                   intgroup = c("Time","Dose"), returnData = TRUE)
ggplot(fiss,
  aes(x = Time, y = count, color = Dose, group = Dose)) + 
  geom_point() + geom_smooth(se = FALSE, method = "loess") + scale_y_log10()




fiss <- plotCounts(ddsTC, "Fmo3",  
                   intgroup = c("Time","Dose"), returnData = TRUE)
ggplot(fiss,
  aes(x = Time, y = count, color = Dose, group = Dose)) + 
  geom_point() + geom_smooth(se = FALSE, method = "loess") + scale_y_log10()

```


